### ISSUE TITLE
Make envScript available

### ISSUE THREAD

**Issue by haslersn** [rrbutani/nix-mk-shell-bin#4]
`mkShellBin` passes an `envScript` to bash via `--rcfile`. For some use cases it might be useful to use the `envScript` directly instead. This way, consumers of this library can choose when and how to source the `envScript`.

One use case that comes to my mind is a docker container where the `envScript` in sourced from `~/.bashrc`. (There might be some additional things in `~/.bashrc`.) This way, users of the container can simply run `/bin/bash` (assuming we made sure that `/bin/bash` exists, e.g. by symlinking it to bash).

Proposed solution: expose the `envScript` as `lib.mkShellRc`

**Comment by rrbutani** [comment]
@haslersn does exposing the env script as a passthrough on the derivation `mkShellBin` gives you work for your use case? i.e.
```nix
let
    pkg = np.hello;
    pkgShellBin = mkShellBin { drv = pkg; nixpkgs = np; };
in
    pkgShellBin.envScript
```

I'd like to keep the interface simple, if possible.
